apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.config.servicename }}
  name: {{ .Values.config.servicename }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.config.replicaNumber }}
  selector:
    matchLabels:
      app: {{ .Values.config.servicename }}
  template:
    metadata:
      labels:
        app: {{ .Values.config.servicename }}
    spec:
      {{- include "cassandra.waitForDatabase" . | nindent 6 }}
      containers:
        - name: {{ .Values.config.servicename }}
          image: "{{ .Values.config.image.repository }}:{{ .Values.config.image.tag }}"
          readinessProbe:
            httpGet:
              path: /ready
              port: management
          livenessProbe:
            httpGet:
              path: /alive
              port: management
          ports:
          - name: management
            containerPort: {{ .Values.config.managementPort }}
            protocol: TCP
          - name: http
            containerPort: {{ .Values.config.httpPort }}
            protocol: TCP
          - name: grpc
            containerPort: {{ .Values.config.grpcPort }}
            protocol: TCP
          resources:
            limits:
              memory: 2Gi
            requests:
              cpu: 2
              memory: 1024Mi
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-location-service-secrets
                  key: rabbitmq-password
            - name: MAPBOX_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-location-service-secrets
                  key: mapbox-api-key
            - name: CASSANDRA_CONTACT_POINT
              value: {{ .Release.Name }}-cassandra.{{ .Release.Namespace }}.svc.cluster.local:9042
            - name: CASSANDRA_USERNAME
              value: {{ .Values.cassandra.dbUser.user | quote }}
            - name: CASSANDRA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-location-service-secrets
                  key: cassandra-password
            - name: RABBITMQ_HOST
              value: "{{ .Values.rabbitmq.serviceName }}.{{ .Values.rabbitmq.namespace }}.svc.cluster.local"
            - name: RABBITMQ_PORT
              value: {{ .Values.rabbitmq.port | quote }}
            - name: RABBITMQ_USERNAME
              value: {{ .Values.rabbitmq.username | quote }}
            - name: GRPC_PORT
              value: {{ .Values.config.grpcPort | quote }}
            - name: HTTP_PORT
              value: {{ .Values.config.httpPort | quote }}
            - name: REQUIRED_CONTACT_POINT_NR
              value: {{ .Values.config.requiredContactPointNr | quote }}